// SPDX-FileCopyrightText: 2026 Martin Schuler
// SPDX-License-Identifier: GPL-3.0-or-later

#include "CrowdFixtures.h"

#include "domain/WordPieceTokenizer.h"
#include "services/CrowdCollector.h"
#include "services/FinBertSentiment.h"

#include <QtTest/QtTest>

#include <QFile>
#include <QTemporaryDir>

using namespace trading::crowd;
using namespace crowdtest;

// The local text-sentiment scorer (REQ-F-044, Phase 6). The tokenizer rules are pure and run
// everywhere; the runner and the collector integration are driven against a TINY bert-shaped
// fixture (tests/make_finbert_fixture.py) — a real FinBERT is a 400 MB download no test suite
// should need — and skip without the optional runtime or the ml environment.
namespace {

QStringList tinyVocab()
{
    return {QStringLiteral("[PAD]"), QStringLiteral("[UNK]"), QStringLiteral("[CLS]"),
            QStringLiteral("[SEP]"), QStringLiteral("profit"), QStringLiteral("##s"),
            QStringLiteral("up"), QStringLiteral("down"), QStringLiteral(","),
            QStringLiteral(".")};
}

bool writeLines(const QString &path, const QStringList &lines)
{
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }
    file.write(lines.join(QLatin1Char('\n')).toUtf8() + "\n");
    return true;
}

// The fixture model directory, generated by the ml venv's python; empty when that is absent.
QString makeFixtureDir(const QTemporaryDir &dir)
{
    const QString python = mlPython();
    if (python.isEmpty()) {
        return {};
    }
    const ToolRun run = runPython(
        python, {repoRoot() + QStringLiteral("/tests/make_finbert_fixture.py"),
                 dir.filePath(QStringLiteral("finbert"))}, 60000);
    return (run.started && run.exitCode == 0) ? dir.filePath(QStringLiteral("finbert"))
                                              : QString();
}

} // namespace

class TestFinBert : public QObject
{
    Q_OBJECT;  // ";" closes the macro for tree-sitter so StrictDoc sees the first slot's marker

private slots:
    //! @tstid TS-FB-001 @design DES-SVC-FINBERT
    // @relation(REQ-F-044, scope=function)
    void TS_FB_001_wordPieceEncodesFaithfullyOrRefusesTheVocabulary()
    {
        const WordPieceVocab vocab = wordPieceVocabFromLines(tinyVocab());
        QVERIFY2(vocab.ok, qPrintable(vocab.error));

        // Lowercase, punctuation split off, greedy LONGEST subword match, [CLS]/[SEP] framing:
        // "Profits up, UP." is [CLS] profit ##s up , up . [SEP].
        QCOMPARE(wordPieceEncode(vocab, QStringLiteral("Profits up, UP."), 16),
                 (QList<qint32>{2, 4, 5, 6, 8, 6, 9, 3}));

        // A word the vocabulary cannot begin is [UNK] WHOLE — matched prefixes of a half-known
        // word would encode a different word than the text held.
        QCOMPARE(wordPieceEncode(vocab, QStringLiteral("zzz up"), 16),
                 (QList<qint32>{2, 1, 6, 3}));

        // Truncation keeps the framing well-formed: the BODY is cut, [SEP] survives.
        const QList<qint32> truncated =
            wordPieceEncode(vocab, QStringLiteral("profits up down up"), 4);
        QCOMPARE(truncated.size(), 4);
        QCOMPARE(truncated.first(), 2);
        QCOMPARE(truncated.last(), 3);

        // A vocabulary without the required specials refuses to encode anything.
        QStringList broken = tinyVocab();
        broken.removeAll(QStringLiteral("[CLS]"));
        const WordPieceVocab refused = wordPieceVocabFromLines(broken);
        QVERIFY(!refused.ok);
        QVERIFY(refused.error.contains(QStringLiteral("special")));
        QVERIFY(wordPieceEncode(refused, QStringLiteral("profit"), 16).isEmpty());
    }

    //! @tstid TS-FB-002 @design DES-SVC-FINBERT
    // @relation(REQ-F-044, scope=function)
    void TS_FB_002_everyMissingPieceIsANamedRefusalNeverAGuess()
    {
        FinBertSentiment scorer;
        QVERIFY(!scorer.ready());
        QVERIFY(!scorer.status().isEmpty());
        QVERIFY(!scorer.scoreText(QStringLiteral("anything")).ok);
        QVERIFY(!scorer.scoreHeadlines({QStringLiteral("anything")}).ok);

        const QTemporaryDir dir;
        QVERIFY(dir.isValid());
        if (!FinBertSentiment::available()) {
            // The stub build is a correct build: unavailable in words that name the remedy.
            QVERIFY2(scorer.status().contains(QStringLiteral("setup.sh ml")),
                     qPrintable(scorer.status()));
            QVERIFY(!scorer.load(dir.path()));
            return;
        }

        // No model file; then a junk model missing its vocabulary; then labels that carry no
        // meaning — each refusal NAMES the missing piece, and nothing half-loads.
        QVERIFY(!scorer.load(dir.path()));
        QVERIFY2(scorer.status().contains(QStringLiteral("model.onnx")),
                 qPrintable(scorer.status()));
        QFile junk(dir.filePath(QStringLiteral("model.onnx")));
        QVERIFY(junk.open(QIODevice::WriteOnly));
        junk.write("not a graph");
        junk.close();
        QVERIFY(!scorer.load(dir.path()));
        QVERIFY2(scorer.status().contains(QStringLiteral("vocab.txt")),
                 qPrintable(scorer.status()));
        QVERIFY(writeLines(dir.filePath(QStringLiteral("vocab.txt")), tinyVocab()));
        QVERIFY(!scorer.load(dir.path()));
        QVERIFY2(scorer.status().contains(QStringLiteral("labels.txt")),
                 qPrintable(scorer.status()));
        QVERIFY(writeLines(dir.filePath(QStringLiteral("labels.txt")),
                           {QStringLiteral("up"), QStringLiteral("down")}));
        QVERIFY(!scorer.load(dir.path()));
        QVERIFY2(scorer.status().contains(QStringLiteral("positive")),
                 qPrintable(scorer.status()));
        // Meaningful labels but an unreadable graph: ONNX Runtime's refusal is carried.
        QVERIFY(writeLines(dir.filePath(QStringLiteral("labels.txt")),
                           {QStringLiteral("positive"), QStringLiteral("negative")}));
        QVERIFY(!scorer.load(dir.path()));
        QVERIFY(!scorer.ready());
        QVERIFY(!scorer.status().isEmpty());
    }

    //! @tstid TS-FB-003 @design DES-SVC-FINBERT
    // @relation(REQ-F-044, scope=function)
    void TS_FB_003_theRunnerScoresTextThroughARealGraphWithLabelledMeaning()
    {
        FinBertSentiment scorer;
        if (!FinBertSentiment::available()) {
            QSKIP("built without ONNX Runtime (./setup.sh ml + reconfigure)");
        }
        const QTemporaryDir dir;
        QVERIFY(dir.isValid());
        const QString fixture = makeFixtureDir(dir);
        if (fixture.isEmpty()) {
            QSKIP("the optional ML environment is not provisioned (./setup.sh ml)");
        }
        QVERIFY2(scorer.load(fixture), qPrintable(scorer.status()));
        QVERIFY(scorer.ready());
        QVERIFY2(scorer.status().contains(QStringLiteral("ready")),
                 qPrintable(scorer.status()));

        // "good" pushes the positive logit in the fixture: a clearly positive text nets
        // strongly positive, a negative one nets negative, and an unknown word contributes
        // NOTHING rather than an invented lean.
        const HeadlineSentiment positive = scorer.scoreText(QStringLiteral("good good news"));
        QVERIFY2(positive.ok, qPrintable(positive.error));
        QCOMPARE(positive.labels.first(), QStringLiteral("positive"));
        QVERIFY2(positive.net > 0.5, qPrintable(QString::number(positive.net)));
        const HeadlineSentiment negative = scorer.scoreText(QStringLiteral("bad"));
        QVERIFY(negative.ok);
        QVERIFY2(negative.net < -0.3, qPrintable(QString::number(negative.net)));

        // The batch reduction: the net over the scored headlines, the count reported, and an
        // empty batch a named error — never a zero sentiment.
        const SocialSentiment batch = scorer.scoreHeadlines(
            {QStringLiteral("good good"), QStringLiteral("bad"), QStringLiteral("good")});
        QVERIFY2(batch.ok, qPrintable(batch.error));
        QCOMPARE(batch.scored, 3);
        QVERIFY(batch.net > 0.0);
        QVERIFY(!scorer.scoreHeadlines({}).ok);
        QVERIFY(!scorer.scoreText(QString()).ok);
    }

    //! @tstid TS-FB-004 @design DES-SVC-FINBERT
    // @relation(REQ-F-044, scope=function)
    void TS_FB_004_theCollectorTurnsHeadlinesIntoASocialObservationOrHonestlyNothing()
    {
        if (!FinBertSentiment::available()) {
            QSKIP("built without ONNX Runtime (./setup.sh ml + reconfigure)");
        }
        const QTemporaryDir dir;
        QVERIFY(dir.isValid());
        const QString fixture = makeFixtureDir(dir);
        if (fixture.isEmpty()) {
            QSKIP("the optional ML environment is not provisioned (./setup.sh ml)");
        }

        qunsetenv("TRADINGAPP_FRED_API_KEY");
        qputenv("TRADINGAPP_CROWD_MODEL", "/nonexistent/crowd-model.onnx");
        qputenv("TRADINGAPP_FINBERT_DIR", fixture.toUtf8());
        {
            CrowdCollector collector(Config{}, dir.filePath(QStringLiteral("crowd.db")));
            bool listed = false;
            const QList<CollectorProviderStatus> statuses = collector.providerStatuses();
            for (const CollectorProviderStatus &status : statuses) {
                listed = listed
                         || (status.name == QStringLiteral("FinBERT") && status.configured);
            }
            QVERIFY(listed);

            // A news batch becomes ONE social observation, hour-quantized: re-scoring inside
            // the same hour is an idempotent no-op, not a flood.
            const int hourBefore = QDateTime::currentDateTimeUtc().time().hour();
            collector.scoreHeadlines(QStringLiteral("SPX500"),
                                     {QStringLiteral("good good"), QStringLiteral("bad")});
            QCOMPARE(collector.store().count(), qint64(1));
            collector.scoreHeadlines(QStringLiteral("SPX500"),
                                     {QStringLiteral("good good"), QStringLiteral("bad")});
            if (QDateTime::currentDateTimeUtc().time().hour() == hourBefore) {
                QCOMPARE(collector.store().count(), qint64(1));
            }

            // The social family is now MEASURED in the model features, with the net value.
            const QHash<QString, double> features = collector.modelFeaturesFor(
                QStringLiteral("SPX500"), QDateTime::currentDateTimeUtc());
            QCOMPARE(features.value(QStringLiteral("social_net_sentiment_measured")), 1.0);
            QVERIFY(features.value(QStringLiteral("social_net_sentiment_value")) > 0.0);
        }

        // Without a model directory: FinBERT reports not configured, and headlines are a
        // silent no-op — no observation, no crash, no invented sentiment. Pointed at nowhere
        // EXPLICITLY: this machine's config dir may hold a real installed model.
        qputenv("TRADINGAPP_FINBERT_DIR", "/nonexistent/finbert");
        CrowdCollector bare(Config{}, dir.filePath(QStringLiteral("bare.db")));
        bare.scoreHeadlines(QStringLiteral("SPX500"), {QStringLiteral("good")});
        QCOMPARE(bare.store().count(), qint64(0));
        bool configured = true;
        const QList<CollectorProviderStatus> statuses = bare.providerStatuses();
        for (const CollectorProviderStatus &status : statuses) {
            if (status.name == QStringLiteral("FinBERT")) {
                configured = status.configured;
            }
        }
        QVERIFY(!configured);
    }
};

QTEST_GUILESS_MAIN(TestFinBert)
#include "tst_finbert.moc"
