# SPDX-FileCopyrightText: 2026 Martin Schuler
# SPDX-License-Identifier: GPL-3.0-or-later

<#
.SYNOPSIS
    Windows counterpart of axivion/start_analysis.sh — run axivion_ci for
    TradingApp.

.DESCRIPTION
    Only one axivion_ci per project: concurrent runs (e.g. build_all.ps1 while a
    manual run is active) share build_axivion\ and delete each other's IR right
    before the dashboard upload. clean_all.ps1 during a run does the same. The
    exclusive lock below is the Windows stand-in for the flock in the .sh.

    Compiler configuration: axivion/compiler_config.json was generated by
    gccsetup on the Linux reference machine and hardcodes /usr/bin/gcc, so it
    cannot describe a Windows build. The Suite has built-in support for the
    Microsoft compiler (no generated profile needed), so this script points
    BAUHAUS_CONFIG at axivion\windows\, whose layer set swaps the GNU profile
    for axivion\compiler_config_msvc.json and shares everything else with the
    Linux configuration by relative path.

    Override with -ConfigDir if you keep a machine-specific configuration
    elsewhere.

.EXAMPLE
    axivion\start_analysis.ps1
    axivion\start_analysis.ps1 --local
    axivion\start_analysis.ps1 -ConfigDir C:\my-axivion-config
#>
[CmdletBinding()]
param(
    # Configuration directory for BAUHAUS_CONFIG. Defaults to axivion\windows.
    [string]$ConfigDir,

    [Parameter(ValueFromRemainingArguments)][string[]]$AxivionArgs = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

. "$PSScriptRoot\..\tools\common.ps1"

# --- single-run lock (the flock equivalent) --------------------------------
$lockPath = Join-Path $env:USERPROFILE '.axivion-TradingApp.lock'
$lock = $null
try {
    $lock = [System.IO.File]::Open($lockPath, 'OpenOrCreate', 'ReadWrite', 'None')
} catch {
    Write-Error "another Axivion run for TradingApp is already active — aborting"
    exit 1
}

try {
    # --- locate the Suite --------------------------------------------------
    # Newest install wins; see Get-AxivionSuite for why the path alone is not a
    # reliable indicator of the version.
    $suite = Get-AxivionSuite
    if (-not $suite) {
        # Exit 3 = "stage skipped" (see build_all.ps1). The Suite is
        # license-bound and setup.ps1 cannot install it, so its absence must not
        # fail the pipeline.
        Write-Skip "the Axivion Suite is not installed (license-bound; .\setup.ps1 cannot install it)."
        Write-Host "         Install it and set BAUHAUS_HOME, or put its bin\ on PATH." -ForegroundColor DarkGray
        exit 3
    }
    $axivionCi = $suite.Ci
    Write-Host "Axivion Suite: $($suite.Root) ($($suite.Version))" -ForegroundColor DarkGray
    # Prepend, so a second installation already on PATH cannot supply the
    # helper executables (cafeCC, the CMake launcher toolchain, …) for this run.
    $env:PATH = "$($suite.Bin);" + (($env:PATH -split ';' | Where-Object { $_ -ne $suite.Bin }) -join ';')
    $env:BAUHAUS_HOME = $suite.Root

    # --- dashboard credentials ---------------------------------------------
    # You may put dashboard credentials inside such a guarded block:
    if (-not $env:AXIVION_USERNAME -and -not $env:AXIVION_PASSWORD -and -not $env:AXIVION_PASSFILE) {
        $env:AXIVION_USERNAME = 'admin'
        $env:AXIVION_PASSWORD = 'password'
    }

    # BAUHAUS_CONFIG points at the directory holding axivion_config.json. On
    # Windows that is axivion\windows\, which reuses the shared layers and swaps
    # in the MSVC compiler profile.
    if (-not $ConfigDir) {
        if ($env:BAUHAUS_CONFIG) { $ConfigDir = $env:BAUHAUS_CONFIG }
        else { $ConfigDir = (Join-Path $PSScriptRoot 'windows') }
    }
    if (-not (Test-Path (Join-Path $ConfigDir 'axivion_config.json'))) {
        Write-Error "no axivion_config.json in $ConfigDir"
        exit 2
    }
    $env:BAUHAUS_CONFIG = (Resolve-Path $ConfigDir).Path
    Write-Host "BAUHAUS_CONFIG: $env:BAUHAUS_CONFIG" -ForegroundColor DarkGray

    # --- toolchain for the build phase -------------------------------------
    $qtPrefix = Resolve-QtPrefix
    if (-not $qtPrefix) {
        Write-Skip "no usable Qt 6 kit found for the analysis build (needs Qt6Charts). Set QT_PREFIX, or run .\setup.ps1 install"
        exit 3
    }

    # Everything else in this repository builds against the NEWEST Qt kit. The
    # Axivion stage is the one exception: Suite 7.12.3's C++ front end asserts
    # while parsing Qt >= 6.10 headers —
    #   Assertion failed: edg::is_at_least_one_error(),
    #   control_flow_expressions.cpp:4168   near QtCore/qvariant.h
    # and IR generation dies ~15 minutes in. Fall back to the newest kit below
    # 6.10 so the stage still produces a dashboard version, and say so out loud.
    # An explicit QT_PREFIX always wins — this only overrides auto-detection.
    if (-not $env:QT_PREFIX) {
        $selected = Get-QtKits | Where-Object { $_.Path -eq $qtPrefix } | Select-Object -First 1
        if ($selected -and $selected.Version -ge [Version]'6.10') {
            $fallback = Get-QtKits | Where-Object { $_.Version -lt [Version]'6.10' } | Select-Object -First 1
            if ($fallback) {
                Write-Host "Qt $($selected.Version) trips a known Axivion front-end assertion (qvariant.h);" -ForegroundColor Yellow
                Write-Host "using $($fallback.Path) for the analysis instead. Override with QT_PREFIX." -ForegroundColor Yellow
                $qtPrefix = $fallback.Path
            } else {
                Write-Warning "only Qt >= 6.10 kits are installed; the Axivion front end may assert on qvariant.h (see docs\windows.md)"
            }
        }
    }
    Add-QtToPath $qtPrefix
    if (Test-QtIsMsvcKit $qtPrefix) {
        if (-not (Import-MsvcEnvironment)) {
            Write-Error "MSVC kit selected but no MSVC toolset found"
            exit 2
        }
    }
    # The Axivion cmake configure doesn't pass -DCMAKE_PREFIX_PATH, so
    # find_package would fall back to a system Qt6 (which lacks Qt6Charts) and
    # fail. Point it at the same Qt the normal build uses; prepend so any
    # existing value still wins.
    if ($env:CMAKE_PREFIX_PATH) {
        $env:CMAKE_PREFIX_PATH = "$qtPrefix;$env:CMAKE_PREFIX_PATH"
    } else {
        $env:CMAKE_PREFIX_PATH = $qtPrefix
    }
    # Consumed by the Frameworks-QtSupport rule in rule_config.json, which must
    # not hardcode a path that exists on only one machine.
    $env:AXIVION_QTDIR = $qtPrefix

    # --jobs (no N) = parallel analysis jobs, auto-sized: cores capped so each
    # job keeps >=2 GB RAM (AXIVION_MIN_MEM_PER_CORE). Placed after the
    # caller's arguments so an explicit -j N still wins; the Ninja build phase
    # is already parallel (native parallelization since Suite 7.11.5).
    & $axivionCi @AxivionArgs --jobs
    exit $LASTEXITCODE
} finally {
    if ($lock) { $lock.Close(); $lock.Dispose() }
}
